### ISSUE TITLE
Add implicit conversion from `Result<T>` to value

### ISSUE THREAD

**Issue by MrDave1999** [MrDave1999/SimpleResults#46]
### Example
```cs
var data = new List<string>();
Result<List<string>> result = Result.Success(data);
// Implicit conversion.
List<string> value = result;
```

**Comment by MrDave1999** [comment]
Yes, you are right, this is dangerous. Back then I created this issue because I was basing it on the Ardalis API, but I didn't consider what you are saying now. So you make a good point.

**Comment by StuartFergusonVme** [comment]
Is there any way this could be changed, even though this could cause many build errors in solutions that use the project.

**Comment by MrDave1999** [comment]
Yes it can be changed, but this introduces a breaking change.

**Comment by MrDave1999** [comment]
Of course yes, I will gladly accept your Pull Request.

**Comment by StuartFergusonVme** [comment]
Raised a PR https://github.com/MrDave1999/SimpleResults/pull/72
